apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: solvency-api-vs
  namespace: solvency-ai
spec:
  hosts:
  - solvency-api.solvency-ai.svc.cluster.local
  http:
  - route:
    - destination:
        host: solvency-api-service
        subset: stable
      weight: 100
    - destination:
        host: solvency-api-service
        subset: canary
      weight: 0
