apiVersion: v1
kind: Service
metadata:
  name: solvency-api-service
  namespace: solvency-ai
spec:
  ports:
  - port: 80
    targetPort: 8000
  selector:
    app: solvency-api
  type: LoadBalancer

---

apiVersion: v1
kind: Service
metadata:
  name: solvency-api-preview
  namespace: solvency-ai
spec:
  ports:
  - port: 80
    targetPort: 8000
  selector:
    app: solvency-api
  type: LoadBalancer
